<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2015/03/31 13:55:28

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:dbname=qdpm;host=localhost',
  'username' => 'aacebo',
  'password' => 'poopie3',
  'attributes' => 
  array (
    'quote_identifier' => true,
  ),
  'name' => 'doctrine',
)),);
