<?php
// auto-generated by sfSecurityConfigHandler
// date: 2015/04/02 19:16:08
$this->security = array (
  'ldap' => 
  array (
    'is_secure' => false,
  ),
  'restorepassword' => 
  array (
    'is_secure' => false,
  ),
  'all' => 
  array (
    'is_secure' => true,
  ),
);
