<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2015/04/01 10:38:28
sfConfig::add(array(
  'mod_projectsstatus_enabled' => true,
  'mod_projectsstatus_view_class' => 'sfPHP',
));
