<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2015/04/01 13:59:40
sfConfig::add(array(
  'mod_projectscomments_enabled' => true,
  'mod_projectscomments_view_class' => 'sfPHP',
));
