<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2015/04/01 11:18:49
sfConfig::add(array(
  'mod_projectsreports_enabled' => true,
  'mod_projectsreports_view_class' => 'sfPHP',
));
