<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2015/04/01 13:59:51
sfConfig::add(array(
  'mod_ticketscomments_enabled' => true,
  'mod_ticketscomments_view_class' => 'sfPHP',
));
