<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2015/04/06 10:30:32
sfConfig::add(array(
  'mod_projectsphases_enabled' => true,
  'mod_projectsphases_view_class' => 'sfPHP',
));
