<?php
// auto-generated by sfSecurityConfigHandler
// date: 2015/03/31 17:46:16
$this->security = array (
  'ldap' => 
  array (
    'is_secure' => false,
  ),
  'restorepassword' => 
  array (
    'is_secure' => false,
  ),
  'all' => 
  array (
    'is_secure' => true,
  ),
);
